default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: react
      password: react

development:
  <<: *default
  database: react_development

production:
      adapter: postgresql
      encoding: unicode
      pool: 5
