default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5

development:
  <<: *default
  database: react_development
  username: react
  password: react
  host:     <%= ENV['IP'] %>

production:
      adapter: postgresql
      encoding: unicode
      pool: 5
