default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: react
      password: react
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: react_development
