Language.create(year:1990, name: 'AMOS BASIC', developer_company: 'François Lionet and Constantin Sotiropoulos')
Language.create(year:1990, name: 'AMPL', developer_company: 'Robert Fourer, David Gay and Brian Kernighan at Bell Laboratories')
Language.create(year:1990, name: 'Object Oberon', developer_company: 'H Mössenböck, J Templ, R Griesemer')
Language.create(year:1990, name: 'J', developer_company: 'Kenneth E. Iverson, Roger Hui at Iverson Software')
Language.create(year:1990, name: 'Haskell', developer_company: ' ')
Language.create(year:1990, name: 'EuLisp', developer_company: ' ')
Language.create(year:1990, name: 'Z Shell (zsh)', developer_company: 'Paul Falstad at Princeton University')
Language.create(year:1991, name: 'GNU E', developer_company: 'David J. DeWitt, Michael J. Carey')
Language.create(year:1991, name: 'Oberon-2', developer_company: 'Hanspeter Mössenböck, Wirth')
Language.create(year:1991, name: 'Python', developer_company: 'Guido van Rossum')
Language.create(year:1991, name: 'Oz', developer_company: 'Gert Smolka and his students')
Language.create(year:1991, name: 'Q', developer_company: 'Albert Gräf')
Language.create(year:1991, name: 'Visual Basic', developer_company: 'Alan Cooper, sold to Microsoft')
Language.create(year:1992, name: 'Borland Pascal', developer_company: ' ')
Language.create(year:1992, name: 'Dylan', developer_company: 'many people at Apple Computer Inc.')
Language.create(year:1993, name: 'Self (implementation)', developer_company: 'Sun Microsystems Inc.')
Language.create(year:1993, name: 'Amiga E', developer_company: 'Wouter van Oortmerssen')
Language.create(year:1993, name: 'Brainfuck', developer_company: 'Urban Müller')
Language.create(year:1993, name: 'LiveCode Transcript', developer_company: ' ')
Language.create(year:1993, name: 'AppleScript', developer_company: 'Apple Computer Inc.')
Language.create(year:1993, name: 'K', developer_company: 'Arthur Whitney')
Language.create(year:1993, name: 'Lua', developer_company: 'Roberto Ierusalimschy et al. at Tecgraf, PUC-Rio')
Language.create(year:1993, name: 'R', developer_company: 'Robert Gentleman and Ross Ihaka')
Language.create(year:1993, name: 'ZPL', developer_company: 'Chamberlain et al. at University of Washington')
Language.create(year:1993, name: 'NewtonScript', developer_company: 'Walter Smith')
Language.create(year:1994, name: 'Claire', developer_company: 'Yves Caseau')
Language.create(year:1994, name: 'ANSI Common Lisp', developer_company: ' ')
Language.create(year:1994, name: 'RAPID', developer_company: 'ABB Group')
Language.create(year:1994, name: 'Pike', developer_company: 'Fredrik Hübinette et al. at Linköping University')
Language.create(year:1994, name: 'ANS Forth', developer_company: 'Elizabeth Rather, et al.')
Language.create(year:1995, name: 'Ada 95', developer_company: 'S. Tucker Taft, et al. at Intermetrics, Inc.')
Language.create(year:1995, name: 'Borland Delphi', developer_company: 'Anders Hejlsberg at Borland')
Language.create(year:1995, name: 'ColdFusion (CFML)', developer_company: 'Allaire')
Language.create(year:1995, name: 'Java', developer_company: 'James Gosling at Sun Microsystems')
Language.create(year:1995, name: 'LiveScript', developer_company: 'Brendan Eich at Netscape')
Language.create(year:1995, name: 'Mercury', developer_company: 'Zoltan Somogyi at University of Melbourne')
Language.create(year:1995, name: 'PHP', developer_company: 'Rasmus Lerdorf')
Language.create(year:1995, name: 'Ruby', developer_company: 'Yukihiro Matsumoto')
Language.create(year:1995, name: 'JavaScript', developer_company: 'Brendan Eich at Netscape')
Language.create(year:1996, name: 'Curl', developer_company: 'David Kranz, Steve Ward, Chris Terman at MIT')
Language.create(year:1996, name: 'Lasso', developer_company: 'Blue World Communications Inc.')
Language.create(year:1996, name: 'Perl Data Language (PDL)', developer_company: 'Karl Glazebrook, Jarle Brinchmann, Tuomas Lukka, and Christian Soeller')
Language.create(year:1996, name: 'OCaml', developer_company: 'INRIA')
Language.create(year:1996, name: 'NetRexx', developer_company: 'Mike Cowlishaw')
Language.create(year:1997, name: 'Component Pascal', developer_company: 'Oberon microsystems, Inc')
Language.create(year:1997, name: 'E', developer_company: 'Mark S. Miller')
Language.create(year:1997, name: 'Pico', developer_company: 'Free University of Brussels')
Language.create(year:1997, name: 'Squeak Smalltalk', developer_company: 'Alan Kay, et al. at Apple Computer Inc.')
Language.create(year:1997, name: 'ECMAScript', developer_company: 'ECMA TC39-TG1')
Language.create(year:1997, name: 'F-Script', developer_company: 'Philippe Mougin')
Language.create(year:1997, name: 'ISLISP', developer_company: 'ISO Standard ISLISP')
Language.create(year:1997, name: 'Tea', developer_company: 'Jorge Nunes')
Language.create(year:1997, name: 'REBOL', developer_company: 'Carl Sassenrath, Rebol Technologies')
Language.create(year:1998, name: 'Standard C++', developer_company: 'ANSI/ISO Standard C++')
Language.create(year:1998, name: 'M2001', developer_company: 'Ronald E. Prather, Trinity University (Texas)')
Language.create(year:1998, name: 'Pikt', developer_company: 'Robert Osterlund (then at University of Chicago)')
Language.create(year:1998, name: 'PureBasic', developer_company: 'Frederic Laboureur, Fantaisie Software')
Language.create(year:1998, name: 'UnrealScript', developer_company: 'Tim Sweeney at Epic Games')
Language.create(year:1999, name: 'XSLT (+ XPath)', developer_company: 'W3C, James Clark')
Language.create(year:1999, name: 'Game Maker Language (GML)', developer_company: 'Mark Overmars')
Language.create(year:1999, name: 'Harbour', developer_company: 'Antonio Linares')
Language.create(year:2000, name: 'Join Java', developer_company: 'G Stewart von Itzstein')
Language.create(year:2000, name: 'ActionScript', developer_company: 'Gary Grossman')
Language.create(year:2000, name: 'Joy', developer_company: 'Manfred von Thun')
Language.create(year:2000, name: 'XL', developer_company: 'Christophe de Dinechin')
Language.create(year:2000, name: 'C#', developer_company: 'Anders Hejlsberg, Microsoft (ECMA)')
Language.create(year:2000, name: 'D', developer_company: 'Walter Bright, Digital Mars')
Language.create(year:2000, name: 'Ferite', developer_company: 'Chris Ross')
Language.create(year:2001, name: 'AspectJ', developer_company: 'Gregor Kiczales, Xerox PARC')
Language.create(year:2001, name: 'Processing', developer_company: 'Casey Reas and Benjamin Fry')
Language.create(year:2001, name: 'Visual Basic .NET', developer_company: 'Microsoft')
Language.create(year:2001, name: 'RPG IV (RPGLE, ILE RPG, RPG Free)', developer_company: 'IBM')
Language.create(year:2001, name: 'GDScript (GDS)', developer_company: 'OKAM Studio')
Language.create(year:2002, name: 'Io', developer_company: 'Steve Dekorte')
Language.create(year:2002, name: 'Gosu', developer_company: 'Guidewire Software')
Language.create(year:2003, name: 'Nemerle', developer_company: 'University of Wrocław')
Language.create(year:2003, name: 'Factor', developer_company: 'Slava Pestov')
Language.create(year:2003, name: 'Falcon', developer_company: 'Giancarlo Niccolai')
Language.create(year:2003, name: 'Scala', developer_company: 'Martin Odersky')
Language.create(year:2003, name: 'Squirrel', developer_company: 'Alberto Demichelis')
Language.create(year:2004, name: 'Subtext', developer_company: 'Jonathan Edwards')
Language.create(year:2004, name: 'Alma-0', developer_company: 'Krzysztof Apt, Centrum Wiskunde & Informatica')
Language.create(year:2004, name: 'Boo', developer_company: 'Rodrigo B. de Oliveira')
Language.create(year:2004, name: 'FreeBASIC', developer_company: 'Andre Victor')
Language.create(year:2004, name: 'Groovy', developer_company: 'James Strachan')
Language.create(year:2004, name: 'Little b', developer_company: 'Aneil Mallavarapu, Harvard Medical School, Department of Systems Biology')
Language.create(year:2005, name: 'F#', developer_company: 'Don Syme, Microsoft Research')
Language.create(year:2005, name: 'Seed7', developer_company: 'Thomas Mertes')
Language.create(year:2006, name: 'Links', developer_company: 'Philip Wadler, University of Edinburgh')
Language.create(year:2006, name: 'Cobra', developer_company: 'ChuckEsterbrook')
Language.create(year:2006, name: 'Windows PowerShell', developer_company: 'Microsoft')
Language.create(year:2006, name: 'OptimJ', developer_company: 'Ateji')
Language.create(year:2007, name: 'Ada 2005', developer_company: 'Ada Rapporteur Group')
Language.create(year:2007, name: 'Fantom', developer_company: 'Brian Frank, Andy Frank')
Language.create(year:2007, name: 'Scratch', developer_company: 'Mitchel Resnick, John Maloney, Natalie Rusk, Evelyn Eastmond, Tammy Stern, Amon Millner, Jay Silver, and Brian Silverman')
Language.create(year:2007, name: 'Vala', developer_company: 'GNOME')
Language.create(year:2007, name: 'Clojure', developer_company: 'Rich Hickey')
Language.create(year:2007, name: 'Fortress', developer_company: 'Guy Steele')
Language.create(year:2007, name: 'Oberon-07', developer_company: 'Wirth[9]')
Language.create(year:2007, name: 'LOLCODE', developer_company: 'Adam Lindsay')
Language.create(year:2008, name: 'Genie', developer_company: 'Jamie McCracken')
Language.create(year:2008, name: 'Pure', developer_company: 'Albert Gräf')
Language.create(year:2009, name: 'Go', developer_company: 'Google')
Language.create(year:2009, name: 'CoffeeScript', developer_company: 'Jeremy Ashkenas')
Language.create(year:2009, name: 'Idris', developer_company: 'Edwin Brady')
Language.create(year:2009, name: 'Parasail', developer_company: 'S. Tucker Taft, AdaCore')
Language.create(year:2010, name: 'Chapel', developer_company: 'Brad Chamberlain, Cray Inc.')
Language.create(year:2010, name: 'Rust', developer_company: 'Graydon Hoare, Mozilla')
Language.create(year:2011, name: 'Ceylon', developer_company: 'Gavin King, Red Hat')
Language.create(year:2011, name: 'Dart', developer_company: 'Google')
Language.create(year:2011, name: 'Elm', developer_company: 'Evan Czaplicki')
Language.create(year:2011, name: 'Kotlin', developer_company: 'JetBrains')
Language.create(year:2011, name: 'C++11', developer_company: 'C++ ISO/IEC 14882:2011')
Language.create(year:2011, name: 'Red', developer_company: 'Nenad Rakocevic')
Language.create(year:2012, name: 'Elixir', developer_company: 'José Valim')
Language.create(year:2012, name: 'TypeScript', developer_company: 'Anders Hejlsberg, Microsoft')
Language.create(year:2012, name: 'Julia', developer_company: 'Jeff Bezanson, Stefan Karpinski, Viral Shah, Alan Edelman, MIT')
Language.create(year:2012, name: 'Ada 2012', developer_company: 'ARA and Ada Europe (ISO/IEC 8652:2012)')
Language.create(year:2014, name: 'Hack', developer_company: 'Facebook')
Language.create(year:2014, name: 'Swift', developer_company: 'Apple Inc.')
Language.create(year:2014, name: 'C++14', developer_company: 'C++ ISO/IEC 14882:2014')
